<?php

// autoload_namespaces.php @generated by Composer

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
);
