<?php

// autoload_psr4.php @generated by Composer

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Sabberworm\\CSS\\' => array($vendorDir . '/sabberworm/php-css-parser/src'),
    'Rmpel\\WpEmailEssentials\\' => array($baseDir . '/src'),
);
