<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitcb92b8d2c931b21248f98bdb4e379d30
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Sabberworm\\CSS\\' => 15,
        ),
        'R' => 
        array (
            'Rmpel\\WpEmailEssentials\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Sabberworm\\CSS\\' => 
        array (
            0 => __DIR__ . '/..' . '/sabberworm/php-css-parser/src',
        ),
        'Rmpel\\WpEmailEssentials\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcb92b8d2c931b21248f98bdb4e379d30::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcb92b8d2c931b21248f98bdb4e379d30::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitcb92b8d2c931b21248f98bdb4e379d30::$classMap;

        }, null, ClassLoader::class);
    }
}
